name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger this action on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Deploy to GitHub Pages using the Personal Access Token for authentication
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # Target branch for GitHub Pages deployment
        folder: .  # Root folder of your static files (no build step needed)
        token: ${{ secrets.GH_TOKEN }}  # Use the GitHub token for authentication
